### PR TITLE
Update html.js

### PR DESCRIPTION
**Pull request by risonipli**
Exclude whitelisted selectors from report.

### CODE REVIEW

**Comment by oyvindeh** [comment]
The white list is case sensitive, so what happens if you write ['html'], instead of ['HTML']? (I guess it shouldn't make any difference, though.)

I am not too familiar with grunt-ucss, as I am not the author. But in theory it shouldn't make any difference.

Perhaps you could send me the configuration where you have specified the whitelist (I assume that would be your Gruntfile) e.g. using gist.github.com? Also, if you run ucss towards a local/internal site, please include some html and css needed to reproduce the error. If you could also include the final report that you get, I will look into this as soon as I can.

**Comment by risonipli** [comment]
Here is my Gruntfile.js, css & html https://gist.github.com/risonipli/5b6e85fb1b241277c868

1. whitelist: ['HTML']

	1 unused CSS selectors found!
	HTML  => dist/demo-ui.css[25]
	.inline  => dist/demo-ui.css[128]
	
2. whitelist: ['HTML', '.inline']. There are no elements with 'include' class in my document.

	You have no unused CSS. Congratulations!

3. whitelist: ['HTML', 'BUTTON']

	1 unused CSS selectors found!
	HTML  => dist/demo-ui.css[25]
	.inline  => dist/demo-ui.css[128]

**Comment by oyvindeh** [comment]
Thanks! I will look into it as soon as I get the chance, although I cannot make any promises as to the timeline.

**Comment by oyvindeh** [comment]
I think this should be fixed now, through the update in grunt-ucss. Please re-open if the problem persists. Sorry that this has taken so long.

**Pull request closed without merging**
